version: "3.1"

services:

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - ".env"
    environment:
      PG_PASSWORD: $PG_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data/


volumes:
  postgres_data: